# All configuration related to navigating files
{
  config,
  lib,
  pkgs,
  ...
}:
{

  extraPackages = with pkgs; [
    fd
  ];

  plugins = {
    oil.enable = true;
    nvim-tree.enable = true;
    flash.enable = true;
    persistence.enable = true;
    harpoon.enable = true; # The name, is the harpoon-maker-agen
    snacks = {
      enable = true;
      luaConfig.pre = # lua
        ''
          -- Open the init.lua config generated by Nixvim
          vim.api.nvim_create_user_command("OpenNixvimConfig", function()
          	local init_path

          	-- First, try to extract from argv (-u)
          	local argv = vim.v.argv
          	for i, a in ipairs(argv) do
          		if a == "-u" and argv[i + 1] then
          			init_path = argv[i + 1]
          			break
          		end
          	end

          	-- Fallback to $MYVIMRC if ever set in future
          	if not init_path or init_path == "" then
          		init_path = vim.fn.expand("$MYVIMRC")
          	end

          	if not init_path or init_path == "" then
          		vim.notify("No init file detected (argv[-u] or $MYVIMRC)", vim.log.levels.ERROR)
          		return
          	end

          	vim.cmd.edit(init_path)
          end, {})
        '';
      settings = {
        dashboard = {
          enabled = true;
          width = 60;
          pane_gap = 1;
          autokeys = "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

          preset = {
            header = ''
              ███╗   ██╗██╗██╗  ██╗██╗   ██╗██╗███╗   ███╗
              ████╗  ██║██║╚██╗██╔╝██║   ██║██║████╗ ████║
              ██╔██╗ ██║██║ ╚███╔╝ ██║   ██║██║██╔████╔██║
              ██║╚██╗██║██║ ██╔██╗ ╚██╗ ██╔╝██║██║╚██╔╝██║
              ██║ ╚████║██║██╔╝╚██╗ ╚████╔╝ ██║██║ ╚═╝ ██║
              ╚═╝  ╚═══╝╚═╝╚═╝  ╚═╝  ╚═══╝  ╚═╝╚═╝     ╚═╝ 26.05
            '';
            keys = [
              {
                icon = " ";
                key = "n";
                desc = "New File";
                action = ":ene | startinsert";
              }
              {
                icon = " ";
                key = "r";
                desc = "Recent Files";
                action = ":lua Snacks.dashboard.pick('oldfiles')";
              }
              {
                icon = " ";
                key = "f";
                desc = "Find File";
                action = ":lua Snacks.dashboard.pick('files')";
              }
              {
                icon = " ";
                key = "g";
                desc = "Find Text";
                action = ":lua Snacks.dashboard.pick('live_grep')";
              }
              {
                icon = " ";
                key = "b";
                desc = "Browse Files";
                action = ":Oil";
              }
              {
                icon = " ";
                key = "c";
                desc = "Config";
                action = ":OpenNixvimConfig";
              }
              {
                icon = " ";
                key = "s";
                desc = "Restore Last Session";
                action = ":lua require('persistence').load({ last = true })";
              }
              {
                icon = " ";
                key = "S";
                desc = "Select Session";
                action = ":lua require('persistence').select()";
              }
              {
                icon = " ";
                key = "q";
                desc = "Quit";
                action = ":qa";
              }
            ];
          };

          sections = [
            {
              section = "header";
              padding = 1;
            }
            {
              header = "Config by Pete3n";
              padding = 0;
            }
            {
              section = "keys";
              padding = 1;
            }
            {
              icon = " ";
              title = "Recent Files";
              section = "recent_files";
              indent = 2;
              padding = 1;
            }

            # Prevent vim.v.oldfiles from hanging on inaccessible directories
            {
              __raw = # lua
                ''
                  Snacks.dashboard.sections.projects({
                    icon = " ",
                    title = "Projects",
                    indent = 2,
                    padding = 1,
                    limit = 8,
                    dirs = {
                      vim.fn.expand("~/projects"),
                      vim.fn.expand("~/code"),
                    },
                  })
                '';
            }

            # Dynamic centered Neovim version footer
            {
              __raw = # lua
                ''
                                    function()
                                      local v = vim.version()
                                      local v_msg = string.format("Neovim %d.%d.%d\n", v.major, v.minor, v.patch)
                  										local uganda = string.format("\nHelp poor children in Uganda!\ntype :help Kuwasha<enter>	for more information\n")
                  										local bram = string.format("RIP Bram Moolenaar 1961-2023")
                  										local msg = v_msg .. uganda .. bram
                                      return { footer = msg, padding = 1 }
                                    end
                '';
            }
          ];
        };
      };
    };
  };

  keymaps = lib.concatLists [
    (lib.optionals config.plugins.flash.enable [
      {
        key = "s";
        mode = [
          "n"
          "x"
          "o"
        ];
        action.__raw = # lua
          ''
            						function()
            							require("flash").jump()
            						end
            					'';
        options = {
          silent = true;
          desc = "Flash";
        };
      }
      {
        key = "S";
        mode = [
          "n"
          "x"
          "o"
        ];
        action.__raw = # lua
          ''
            						function()
            							require("flash").treesitter()
            						end
            					'';
        options = {
          silent = true;
          desc = "Flash Treesitter";
        };
      }
      {
        key = "r";
        mode = "o";
        action.__raw = # lua
          ''
            						function()
            							require("flash").remote()
            						end
            					'';
        options = {
          silent = true;
          desc = "Remote Flash";
        };
      }
      {
        key = "R";
        mode = [
          "o"
          "x"
        ];
        action.__raw = # lua
          ''
            						function()
            							require("flash").treesitter_search()
            						end
            					'';
        options = {
          silent = true;
          desc = "Treesitter Search";
        };
      }
      {
        key = "<C-s";
        mode = "c";
        action.__raw = # lua
          ''
            						function()
            							require("flash").toggle()
            						end
            					'';
        options = {
          silent = true;
          desc = "Toggle Flash Search";
        };
      }
    ])
    (lib.optionals config.plugins.oil.enable [
      {
        key = "<leader>nv";
        mode = "n";
        action = "<cmd>Oil<CR>";
        options = {
          silent = true;
          desc = "view filetree";
        };
      }
    ])
    (lib.optionals config.plugins.nvim-tree.enable [
      {
        key = "<leader>nt";
        mode = "n";
        action = "<cmd>NvimTreeToggle<CR>";
        options = {
          silent = true;
          desc = "toggle filetree";
        };
      }
    ])
    (lib.optionals config.plugins.harpoon.enable [
      {
        key = "<leader>na";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():add()<CR>";
        options = {
          silent = false;
          desc = "add file to 󱡅 harpoon (󱁐 a)";
        };
      }
      {
        key = "<leader>a";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():add()<CR>";
        options = {
          silent = false;
          desc = "add file to 󱡅 harpoon";
        };
      }
      {
        key = "<leader>ne";
        mode = "n";
        action = "<cmd>lua require('harpoon').ui:toggle_quick_menu(require('harpoon'):list())<CR>";
        options = {
          silent = true;
          desc = "harpoon menu (󰘴 E)";
        };
      }
      {
        key = "<C-e>";
        mode = "n";
        action = "<cmd>lua require('harpoon').ui:toggle_quick_menu(require('harpoon'):list())<CR>";
        options = {
          silent = true;
          desc = "harpoon menu";
        };
      }
      {
        key = "<leader>n1";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(1)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 2 (󰘴 H)";
        };
      }
      {
        key = "<C-h>";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(1)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 1";
        };
      }
      {
        key = "<leader>n2";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(2)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 2 (󰘴 T)";
        };
      }
      {
        key = "<C-t>";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(2)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 2";
        };
      }
      {
        key = "<leader>n3";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(3)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 3 (󰘴 N)";
        };
      }
      {
        key = "<C-n>";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(3)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 3";
        };
      }
      {
        key = "<leader>n4";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(4)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 4 (󰘴 S)";
        };
      }
      {
        key = "<C-s>";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(4)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 4";
        };
      }
      {
        key = "<leader>n5";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(5)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 5";
        };
      }
      {
        key = "<leader>n6";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(6)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 6";
        };
      }
      {
        key = "<leader>n7";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(7)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 7";
        };
      }
      {
        key = "<leader>n8";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(8)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 8";
        };
      }
      {
        key = "<leader>n9";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(9)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 9";
        };
      }
      {
        key = "<leader>n0";
        mode = "n";
        action = "<cmd>lua require('harpoon'):list():select(0)<CR>";
        options = {
          silent = true;
          desc = "harpoon file 10";
        };
      }
    ])
    (lib.optionals config.plugins.snacks.settings.dashboard.enabled [

      {
        key = "<leader>nd";
        mode = "n";
        action = "<cmd>lua require('snacks').dashboard()<CR>";
        options = {
          silent = true;
          desc = "dashboard";
        };
      }
    ])
  ];

  extraConfigLuaPost = # lua
    ''
            if wk_available then
            	local keymaps = {}

            	-- Unconditional searching group mapping
            	table.insert(keymaps, { "<leader>n", group = "navigating", icon = " " })

            	-- Conditionall map harpoon icons
            	if pcall(require, "harpoon") then
            		table.insert(keymaps, { "<leader>a", icon = " " })
            		table.insert(keymaps, { "<leader>na", icon = " " })
            		table.insert(keymaps, { "<leader>ne", icon = "󰮫 ", })
            		table.insert(keymaps, { "<C-e>", icon = "󰮫 ", })
            		table.insert(keymaps, { "<leader>n1", icon = "󱡅 ", })
            		table.insert(keymaps, { "<C-h>", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n2", icon = "󱡅 ", })
            		table.insert(keymaps, { "<C-t>", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n3", icon = "󱡅 ", })
            		table.insert(keymaps, { "<C-n>", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n4", icon = "󱡅 ", })
            		table.insert(keymaps, { "<C-s>", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n5", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n6", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n7", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n8", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n9", icon = "󱡅 ", })
            		table.insert(keymaps, { "<leader>n0", icon = "󱡅 ", })
            	end

            	-- Conditionall map oil icon
            	if pcall(require, "oil") then
            		table.insert(keymaps, { "<leader>nv", icon = "󰏇 ", })
            	end

            	-- Conditionall map nvim-tree icon
            	if pcall(require, "nvim-tree") then
            		table.insert(keymaps, { "<leader>nt", icon = " ", })
            	end

            	-- Conditionall map flash 
            	if pcall(require, "flash") then
            		table.insert(keymaps, { "s", mode = { "n", "x", "o" }, icon = "⚡", desc = "Flash" })
            		table.insert(keymaps, { "S", mode = { "n", "x", "o" }, icon = "⚡🌳 ", desc = "Flash Treesitter" })
            		table.insert(keymaps, { "r", mode = "o", icon = "🌐⚡ ", desc = "Remote Flash" })
            		table.insert(keymaps, { "R", mode = { "o", "x" }, icon = "🌳🔎 ", desc = "Treesitter Search" })
            		table.insert(keymaps, { "<C-s>", mode = "c", icon = "󰔡 ⚡ ", desc = "Toggle Flash" })
            	end

      				-- Conditional map snacks dashboard
      				if pcall(require, "snacks.dashboard") then
            		table.insert(keymaps, { "<leader>nd", mode = "n", icon = "󰻎 ", desc = "Dashboard" })
      				end

            	wk.add(keymaps)
            end
    '';
}
